### ISSUE TITLE
Auto-remove ❗reaction on flagged messages

### ISSUE THREAD

**Issue by i-am-gizm0** [wpi-25/gompei25#34]
**Is your feature request related to a problem? Please describe.**
Currently when a user flags a message, the reaction stays there and calls attention to the message when sometimes it shouldn't be called out

**Describe the solution you'd like**
After the bot has forwarded the message, it should remove the reaction as a confirmation

**Describe alternatives you've considered**
Idk, a message action? Nothing really, this was brainstormed irl with @Muirrum 

**Additional context**
No :)

**Comment by Muirrum** [comment]
message action would be nice but it would also require adding interactions
