### ISSUE TITLE
Mod commands

### ISSUE THREAD

**Issue by i-am-gizm0** [wpi-25/gompei25#9]
- [ ] `clear` - Clear a certain number of messages
- [ ] `clearreaction` - Clear certain reactions from a channel
- [ ] `dmpurgatory` - ~~never~~ rarely used; DM all users without access to most of the server
- [ ] `lvlclear` - Should be replaced; Allows clearing a user from the db
- [ ] `sendmsg` - Send a message in a channel  
*Some other commands that* would *fit in this category either wouldn't work in a Docker container or wouldn't work the same/at all in Rust*

**Comment by Muirrum** [comment]
Can you elaborate on the last task? Which commands wouldn't work, and why?

**Comment by i-am-gizm0** [comment]
Mostly the 'lifetime' commands: shutdown/restart because it depends on the `restart:` value of the container.
I'm also not sure if dynamic loading of commands is possible but given Rust is compiled, I assume it wouldn't be easy.

**Comment by Muirrum** [comment]
There's no dynamic loading of commands. You can pass an array of command names at compile time (or runtime with some clever use of config files). See https://git.sr.ht/~muirrum/campmasterconstantine/tree/master/item/src/main.rs#L281 for an example.

**Comment by Muirrum** [comment]
What do you want to see out of `clearreaction`?
